### ISSUE TITLE
Missing Typescript example

### ISSUE THREAD

**Issue by christher-lenander** [advanced-cropper/vue-advanced-cropper#163]
Your examples don't work out of the box when using Vue 3 and Typescript.

**Comment by Norserium** [comment]
@ChristherLenander, hello! What's exactly goes wrong or not clear?

**Comment by Norserium** [comment]
@ChristherLenander, any news?

**Comment by Norserium** [comment]
@DannyFeliz, do you have the same issue? Could you give me some details?

**Comment by zynth17** [comment]
got the same issues, there is not type for cropperRef element so there is no possible way to call getResult() from cropperRef element on composition api

**Comment by Norserium** [comment]
@zynth17, I were not sure that it should be documented. It looks like the common Vue 3 practice:
```ts
const cropper = ref<InstanceType<typeof Cropper>>();

if (cropper.value) {
   const result = cropper.value.getResult();
}
```

It is described in [the official documentation](https://v3.vuejs.org/guide/typescript-support.html#typing-template-refs).

**Comment by zynth17** [comment]
> @zynth17, I were not sure that it should be documented. It looks like the common Vue 3 practice:
> 
> ```ts
> const cropperRef = ref<InstanceType<typeof Cropper>>();
> 
> if (cropperRef.value) {
>    const result = cropperRef.value.getResult();
> }
> ```
> 
> It is described in [the official documentation](https://v3.vuejs.org/guide/typescript-support.html#typing-template-refs).

thanks! totally forgot can do this.
