### ISSUE TITLE
how to use it without npm?

### ISSUE THREAD

**Issue by jinfagang** [advanced-cropper/vue-advanced-cropper#191]
just vanilla html, how to using this

**Comment by Norserium** [comment]
@jinfagang, there is [the guide](https://norserium.github.io/vue-advanced-cropper/introduction/getting-started.html#using-cdn) in the documentation how to use it without NPM.

**Comment by Norserium** [comment]
@jinfagang, any news?

**Comment by Norserium** [comment]
@jinfagang, any news?

**Comment by Norserium** [comment]
@jinfagang, I close issue, feel free to reopen it.
