### ISSUE TITLE
Rendered Size of image is 0

### ISSUE THREAD

**Issue by RuhiuEdwin** [advanced-cropper/vue-advanced-cropper#200]
I am new to vue-adnavced-cropper, i tested it out as documented and it worked perfectly with unsplash images, but when I refactored to use with images fetched from my database, the image's was rendered as detailed below

Rendered size: | 16 × 0 px
-- | --
Rendered aspect ratio: | 1∶0
Intrinsic size: | 1520 × 2048 px
Intrinsic aspect ratio: | 95∶128
File size: | 232 kB

how can I change the rendered size?

**Comment by Norserium** [comment]
@RuhiuEdwin, any news?

**Comment by Norserium** [comment]
@RuhiuEdwin, any news?

**Comment by Norserium** [comment]
@RuhiuEdwin, I close issue, feel free to reopen it.
