### ISSUE TITLE
Error: Cannot read property 'aspectRatios' of undefined

### ISSUE THREAD

**Issue by itsamirhn** [advanced-cropper/vue-advanced-cropper#207]
In some use cases, some of our users get this error: 

> Cannot read property 'aspectRatios' of undefined

and It's accruing in this [line](https://github.com/advanced-cropper/vue-advanced-cropper/blob/e1df48e2f13bb5e420385956751b83625be2bdfb/src/Cropper.vue#L1197).

Would you please help me what's the problem?

**Comment by Norserium** [comment]
@itsamirhn, this error is indeed theoretically possible.But the conditions are not clear at all. How did you get this information? Did you get it from Sentry?

**Comment by itsamirhn** [comment]
> @itsamirhn, this error is indeed theoretically possible.But the conditions are not clear at all. How did you get this information? Did you get it from Sentry?

Yes it was from Sentry, Do you need any more information?

**Comment by Norserium** [comment]
@itsamirhn, the full trace log would be helpful.

**Comment by Norserium** [comment]
@itsamirhn, I assume it's possible if an user change something and within 500 ms swaps to an another page, but it should be pretty rare case. 

How often is this error (in particular, relative to another errors)?

**Comment by Norserium** [comment]
@itsamirhn, how much cases? Could you send the full screenshot of your issue to my email?

**Comment by itsamirhn** [comment]
> We are also experiencing this error, in our case the cropper is inside a modal, when I am uploading an image and at the moment of resizing the stencil I drag the mouse out of the modal is when the error shows up.
> 
> 
> 
> It may be that dragging the mouse out of the modal closes it and unmounts the cropper component, but I'm not sure.

Oh same, we're using it in a modal view.

**Comment by Norserium** [comment]
@itsamirhn, @emmanuelsw, try to update to `1.11.3` (if you use Vue 2, of course).

**Comment by itsamirhn** [comment]
After some testings, It seems the problems was when I was using cropper as modal ([Vuetify v-dialog](https://vuetifyjs.com/en/components/dialogs/) in this case) and a stepper in the background ([Vuetify v-window ](https://vuetifyjs.com/en/components/windows/) in this case) and when the user stretch the crop border outside the modal, stepper was going to the next page and causes the error.

At the end, disabling manual swipe on stepper and updating to version `1.11.3` solved the issue.

**Comment by Norserium** [comment]
@itsamirhn, did you try update to version `1.11.3` only? It would be helpful for me.

**Comment by itsamirhn** [comment]
> @itsamirhn, did you try update to version `1.11.3` only (without any other fixes)? It would be helpful for me.

Yes, And it was fine. Thanks for your update.

**Comment by Norserium** [comment]
@itsamirhn, it's great!
