### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by RPainter8West** [advanced-cropper/vue-advanced-cropper#210]
Please update the NPM dependencies to include Vue v3+
![image](https://user-images.githubusercontent.com/53478701/185554825-8fb3d6c3-4924-4ebc-8e45-4d65b0b08a62.png)

**Comment by Norserium** [comment]
@RPainter8West, I see that you tried to install `vue-advanced-cropper@1.11.3`. This version is designed for Vue 2. To install this library for Vue 3 install the next version: `vue-advanced-cropper@~2.8.3`.

**Comment by Norserium** [comment]
@RPainter8West, any news?

**Comment by RPainter8West** [comment]
Sorry, my fault. I didn't see the other package version.
