### ISSUE TITLE
Reset method fire this.$refs.stencil is null

### ISSUE THREAD

**Issue by rustre-undefined** [advanced-cropper/vue-advanced-cropper#213]
Hello I call reset method on a ref of Cropper component and I have this error `Uncaught TypeError: this.$refs.stencil is null`, if any of you have an idea to solve that. Thanks for your time!

Codebase intentionaly simplified:
```jsx
<script setup>
// Import here

const my_cropper = ref(null);

function reset() 
  my_cropper.value.reset();
}
</script>

<template>
  <Cropper ref="my_cropper" />

  <button @click="reset()">Reset</button>
</template>
```

**Comment by Norserium** [comment]
@rustre-undefined, hello. Could you reproduce this issue on sandbox?

**Comment by Norserium** [comment]
@rustre-undefined, try to update to `2.8.6`. Perhaps, it could help.

**Comment by rustre-undefined** [comment]
Sorry I haven't seen the answer :/
It was a mistake due the async behavior of image loading, everything is okay with the dependency!

**Comment by Norserium** [comment]
@rustre-undefined, all well that ends well.
