### ISSUE TITLE
Can't get the current zoom level

### ISSUE THREAD

**Issue by Emaxoso** [advanced-cropper/vue-advanced-cropper#218]
I don't know if this is a bug or a missing feature. 
I am trying to get the current zoom of the cropper, since for security reasons I need to crop on the server side, I was trying to find the image scale size.

I'm using the next branch

**Comment by Norserium** [comment]
@Emaxoso, hello!

First of all, why do you need to get the current zoom? To get the selected area you need coordinates only, they represent that area.

```js
const { coordinates } = this.$refs.cropper.getResult();
```

If you really need to get the current zoom, you should know that there is not concept of absolute zoom. There is the `visibleArea` property that represents the current visible area of an image.

**Comment by Emaxoso** [comment]
> First of all, why do you need to get the current zoom? To get the selected area you need coordinates only, they represent that area.
I use the zoom to resize the image. First I do the cropping with the coordinates then I use the zoom to enlarge the image.

I was able to track the zoom by extending the Cropper component.
```
export default defineComponent({
	extends: Cropper,
	emits: ['scale'],
	watch: {
		src() {
			this.scale = 1.0;
		},
		scale() {
			this.$emit("scale", Math.round(this.scale * 1000) / 1000);
		}
	},
	data: () => ({
		scale: 1.0
	}),
	methods: {
		onManipulateImage(event, params = {}) {
			if (event && event.scale) {
				this.scale = Math.max(1, this.scale + 1 - event.scale.factor);
			}
			Cropper.methods.onManipulateImage.call(this, event, params);
		},
	},
});
```

**Comment by Norserium** [comment]
> First I do the cropping with the coordinates then I use the zoom to enlarge the image.

@Emaxoso, I still don't get why? Should the following images have the different sizes?
![image](https://user-images.githubusercontent.com/9862719/200118993-3adb6095-dd8f-4cd5-9f93-96fa292c9b45.png)
![image](https://user-images.githubusercontent.com/9862719/200119050-530fb44a-bb8f-4c31-b7bc-cfb40eb4e72b.png)

It's pretty strange, because the cropped part is the same in both cases.

**Comment by dala00** [comment]
I also want to get current zoom level.
Because zoom level is specified by other indicator UI on our app.
Or I want to 'specify' zoom level of cropper.

**Comment by Norserium** [comment]
@dala00, I assume you want to get something like [this](https://codesandbox.io/s/vue-advanced-cropper-twitter-suoyc)?

**Comment by dala00** [comment]
Oh, yes!

**Comment by Norserium** [comment]
@dala00,  @Emaxoso is this issue still actual?

**Comment by dala00** [comment]
I changed library (needed for job then)
