### ISSUE TITLE
Vue3 can not move stencil

### ISSUE THREAD

**Issue by robertexplodes** [advanced-cropper/vue-advanced-cropper#219]
I am using Vue3 and added this library to my code.
I simply can select an image, and also resize the stencil, but I cant move the stencil around.
Also the area within the stencil has the same brightness as the image below.
When trying to move the stencil only the image will move (Only if zoomed).

![image](https://user-images.githubusercontent.com/56740540/204567924-44e2699f-4415-4aa8-9569-6ab9abdafad0.png)

```javascript
<cropper stencil-component="rectangle-stencil" class="cropper mt-3"  :src="image" @change="change" />
```
I globally mounted the RectangleStencil component.

**Comment by Norserium** [comment]
@robertexplodes, just a guess, do you have somewhere the following styles?
```css
* {
    position: relative;
}
```

**Comment by robertexplodes** [comment]
@Norserium thank you, it works now!

**Comment by Norserium** [comment]
@robertexplodes, you are welcome!
