### ISSUE TITLE
Show full size image after a rotation 

### ISSUE THREAD

**Issue by stanleyxu2005** [advanced-cropper/vue-advanced-cropper#220]
I'm facing the [same issue](https://github.com/advanced-cropper/vue-advanced-cropper/issues/208) here. 

Just take this official demo as example
https://codesandbox.io/s/vue-advanced-cropper-preview-experimental-fixed-aspect-ratio-eo9ed?file=/src/App.vue

The image is width=540, height=841 (rectangle)
After the image is rotated, the visiable area becomes a square. 

![image](https://user-images.githubusercontent.com/5162687/205306475-fed3568b-2d2c-456c-9768-2ef47fcc4a5c.png)
![image](https://user-images.githubusercontent.com/5162687/205306596-a7eea0a4-a6e0-452b-92c9-080cd32ff0e2.png)

Is it possible to make the image to be shown as "contain" mode, so that it is still show the full image, just like this?
![image](https://user-images.githubusercontent.com/5162687/205307326-baeb55fe-a13b-4933-8b3f-0dcbfb95d788.png)

**Comment by Norserium** [comment]
@stanleyxu2005, that's how the default rotate algorithm works. It tries to preserve the original selected area on rotate as much as it possible.

Let's try to make clear what you want to get. What if, for example, the image was already zoomed and you rotate it?

**Comment by stanleyxu2005** [comment]
Hi @Norserium. Thank you for the quick response.

The expectation is
1. User makes a cropped area

**Comment by Norserium** [comment]
@stanleyxu2005, I got it. This behavior can be easily over-defined in the future major version, but currently it's pretty tough task.  How is critical this issue for you?

**Comment by stanleyxu2005** [comment]
I tried to fiddle with `imageClass`, `foregroundClass` etc., but no luck. So I guess tweak zoom might work. If it is not confirmed by repo owner, then I have to wait :D

BTW, I'm currently using Vue 2. But I dont see any challenges if I switch projects to Vue 3.

**Comment by Norserium** [comment]
> BTW, I'm currently using Vue 2. But I dont see any challenges if I switch projects to Vue 3.

I'm just going to support only Vue 2.7 / Vue 3 in the future due to using of Composition API under the hood in the new major release.

**Comment by stanleyxu2005** [comment]
I managed to use the following code as a workaround.
```
rotateAndFixImageSize() { 
      this.$refs.cropper.rotate(90)
      setTimeout(() => {
          this.resetImageSize()
      }, 500)
}

resetImageSize() {
    this.$refs.cropper.zoom(0.001)
}
```

Looking forward to your next major version

**Comment by hanzhenfang** [comment]
What about this problem now？I face the same issue.

**Comment by Norserium** [comment]
@hanzhenfang, I assume you want to get something like this in [`react-advanced-cropper`](https://codesandbox.io/s/react-advanced-cropper-rotate-with-basis-4eymkn?file=/src/algorithms.tsx)?

**Comment by hanzhenfang** [comment]
I did it from the other side， when I first load the Cropper component, I will record an object named "primitiveStencilRect". It is assigned on the "defaultSize" props callback first invoked.

![image](https://user-images.githubusercontent.com/99874763/232403658-4c565a53-9852-4541-a8b2-ba937e1832ac.png)

![image](https://user-images.githubusercontent.com/99874763/232403728-ccbf6eb2-2e16-4904-8763-f0d185623f3f.png)

then I will use it for every rotate event.

![image](https://user-images.githubusercontent.com/99874763/232404121-879b0c8a-847d-45ce-a987-ed9dacd7b42b.png)

tips: pay attention to the "width" and "height" at different degrees.😄

**Comment by hanzhenfang** [comment]
Hope some help for somebody.

**Comment by hanzhenfang** [comment]
@Norserium Thanks you also for you reply~😊

**Comment by atomiomi** [comment]
Hey @hanzhenfang @Norserium is there a solution for this?
I've tried all the solutions above and they don't seem to work.

**Comment by JakobBernoulli** [comment]
+1

**Comment by JakobBernoulli** [comment]
> Hey [@hanzhenfang](https://github.com/hanzhenfang) [@Norserium](https://github.com/Norserium) is there a solution for this? I've tried all the solutions above and they don't seem to work.

@atomiomi I've found the following solution for myself. It might help you with your project as well. After the rotation, I set the zoom. I have the `resizeImage` prop set to `false` by default, but I need to set it to `true` before adjusting the zoom for it to work. After that, it's set back to `false`.

```
const resizeImage = ref(false);

const rotate = () => {

  cropper.value?.rotate(90);

  resizeImage.value = true;
  setTimeout(() => {
    cropper.value?.zoom(0.5);
    resizeImage.value = false;
  }, 500);

};

<template>

  <Cropper
    ref="cropper"
    class="cropper"
    image-restriction="fit-area"
    :src="image || props.img"
    :resizeImage="resizeImage"
    @change="change"
  />

</template>
```
