### ISSUE TITLE
Cant Draw Rectangle On Image

### ISSUE THREAD

**Issue by EnesCeltikk** [advanced-cropper/vue-advanced-cropper#221]
Hi, when I click the button, I want to get the coordinate values of the RectangleStencil and draw a rectangle on the photo. My draw code is below, its not working. Nothing happens on the screen. How can i draw rectangle on image? Thanks.

![image](https://user-images.githubusercontent.com/44348669/206543203-abad6467-0385-4d7c-9607-b44cfde6a112.png)

**Comment by Norserium** [comment]
@EnesCeltikk, try [this example](https://codesandbox.io/s/vue-advanced-cropper-canvas-experiments-dzvb22). Did I understand you correctly?

**Comment by EnesCeltikk** [comment]
Yes this is what i need exactly. Thank you very much.

What can I do so that the previous drawn rectangles don't delete when the key is pressed? I want to draw multiple rectangles on the photo

**Comment by Norserium** [comment]
You shouldn't redraw the image on the canvas in this case.

**Comment by EnesCeltikk** [comment]
Hello again, 

I want to draw the red rectangle on the photo where the stencil square is. Not in another photo. What should I use to make changes to the photo we crop?

Example image;
![image](https://user-images.githubusercontent.com/44348669/206712472-397939dd-bf32-4119-97f2-af8ae070fc9e.png)

**Comment by Norserium** [comment]
@EnesCeltikk, do you want to achieve something [like this](https://codesandbox.io/s/vue-advanced-cropper-canvas-experiments-extension-0qkwoo)?
