### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by waysagency** [advanced-cropper/vue-advanced-cropper#225]
npm install -S vue-advanced-cropper

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\USERNAME\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USERNAME\AppData\Local\npm-cache\_logs\2022-12-22T18_58_09_345Z-debug-0.log

## Full log
0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@8.11.0
2 info using node@v16.16.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 12ms
6 timing config:load:builtin Completed in 12ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\personal\vue-playground\.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:C:\Users\USERNAME\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\USERNAME\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 28ms
19 timing npm:load:configload Completed in 28ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm install vue-advanced-cropper
23 verbose argv "install" "--save" "vue-advanced-cropper"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 5ms
26 timing npm:load:display Completed in 7ms
27 verbose logfile logs-max:10 dir:C:\Users\USERNAME\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\USERNAME\AppData\Local\npm-cache\_logs\2022-12-22T18_58_09_345Z-debug-0.log
29 timing npm:load:logFile Completed in 16ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 56ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 2 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 291ms
37 timing idealTree:userRequests Completed in 7ms
38 silly idealTree buildDeps
39 silly fetch manifest vue-advanced-cropper@*
40 timing arborist:ctor Completed in 0ms
41 http fetch GET 200 https://registry.npmjs.org/vue-advanced-cropper 1057ms (cache revalidated)
42 silly fetch manifest vue@^3.2.45
43 http fetch GET 200 https://registry.npmjs.org/vue 63ms (cache revalidated)
44 silly fetch manifest vue@^2.6.6
45 timing idealTree Completed in 1457ms
46 timing command:install Completed in 1479ms
47 verbose stack Error: unable to resolve dependency tree
47 verbose stack     at Arborist.[failPeerConflict] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1428:25)
47 verbose stack     at Arborist.[loadPeerSet] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1394:34)
47 verbose stack     at async Arborist.[buildDepStep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:976:11)
47 verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:218:7)
47 verbose stack     at async Promise.all (index 1)
47 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:153:5)
47 verbose stack     at async Install.exec (C:\Program Files\nodejs\node_modules\npm\lib\commands\install.js:156:5)
47 verbose stack     at async module.exports (C:\Program Files\nodejs\node_modules\npm\lib\cli.js:78:5)
48 verbose cwd C:\personal\vue-playground
49 verbose Windows_NT 10.0.22000
50 verbose node v16.16.0
51 verbose npm  v8.11.0
52 error code ERESOLVE
53 error ERESOLVE unable to resolve dependency tree
54 error
55 error While resolving: [1mvue-playground[22m@[1m0.0.0[22m
55 error Found: [1mvue[22m@[1m3.2.45[22m[2m[22m
55 error [2mnode_modules/vue[22m
55 error   [1mvue[22m@"[1m^3.2.45[22m" from the root project
55 error
55 error Could not resolve dependency:
55 error [35mpeer[39m [1mvue[22m@"[1m^2.6.6[22m" from [1mvue-advanced-cropper[22m@[1m1.11.5[22m[2m[22m
55 error [2mnode_modules/vue-advanced-cropper[22m
55 error   [1mvue-advanced-cropper[22m@"[1m*[22m" from the root project
55 error
55 error Fix the upstream dependency conflict, or retry
55 error this command with --force, or --legacy-peer-deps
55 error to accept an incorrect (and potentially broken) dependency resolution.
55 error
55 error See C:\Users\USERNAME\AppData\Local\npm-cache\eresolve-report.txt for a full report.
56 verbose exit 1
57 timing npm Completed in 1757ms
58 verbose unfinished npm timer reify 1671735489597
59 verbose unfinished npm timer reify:loadTrees 1671735489613
60 verbose unfinished npm timer idealTree:buildDeps 1671735489912
61 verbose unfinished npm timer idealTree:#root 1671735489913
62 verbose code 1
63 error A complete log of this run can be found in:
63 error     C:\Users\USERNAME\AppData\Local\npm-cache\_logs\2022-12-22T18_58_09_345Z-debug-0.log

**Comment by Norserium** [comment]
@waysagency, try to execute:
```
npm install -S vue-advanced-cropper@next
 ```

**Comment by waysagency** [comment]
Hi @Norserium,

Pff, didn't see it at all. Maybe it would be good to add this to the homepage as well?

**Comment by Norserium** [comment]
@waysagency, actually it's.

![image](https://user-images.githubusercontent.com/9862719/209291768-b22c6f79-7fc8-48ea-9c2c-c2be8dd4a878.png)


I will set `latest` tag for the versions for Vue 3 and clarify this aspect in `README.md` also.

**Comment by Norserium** [comment]
@waysagency, the `latest` tag is switched to the version for Vue 3.
