### ISSUE TITLE
Feature Request Extend Crop Data in getResult

### ISSUE THREAD

**Issue by nseb** [advanced-cropper/vue-advanced-cropper#226]
Hello,
I find the library really good because it is very complete, for me it would lack more exhaustive information when you do a flip, rotae or zoom to retrieve the information in the getResult like the coordinates of the crop.
A bit like in this [example:](https://fengyuanchen.github.io/cropperjs/)

Best Regards

**Comment by Norserium** [comment]
@nseb, I'm currently rewriting this library to correspond the API of `react-advanced-cropper`, so the `getResult` will be deleted. You will be able to get the desired result by [`getTransforms`](https://advanced-cropper.github.io/react-advanced-cropper/docs/components/Cropper/#gettransforms) method.

Currently you can get the transforms from `image` property:
```ts
const result = this.$refs.cropper?.getResult();
if (result) {
    const { transforms } = result.image;
}
```

**Comment by nseb** [comment]
@Norserium , thank you for your return it works, the telegram version in react is great ;-)

**Comment by Norserium** [comment]
@nseb, you are welcome!

> the telegram version in react is great ;-)

The good news is it will be ported to Vue too.

**Comment by nseb** [comment]
@Norserium thanks ;-) , sorry for the late reply
