### ISSUE TITLE
Need fix vue version on jsfieddle sandbox

### ISSUE THREAD

**Issue by HtmlMak** [advanced-cropper/vue-advanced-cropper#227]
Hi! By default, the third version is downloaded and this breaks the example. You can install one of the stable versions like 2.6.14?
Here: https://jsfiddle.net/norserium/38u4v9nb/

**Comment by Norserium** [comment]
@HtmlMak, I've replaced the JSFiddle examples by the CodeSandbox examples and resolve this issue. Check it.

**Comment by HtmlMak** [comment]
@Norserium can then use codeSandbox as examples on [docs](https://advanced-cropper.github.io/vue-advanced-cropper/introduction/getting-started.html#using-cdn)?
ps: sorry if you don't support this site :)

**Comment by Norserium** [comment]
@HtmlMak, it should be updated now, there was a little mistake. Check it now.

**Comment by HtmlMak** [comment]
@Norserium yeah, thanks!

**Comment by Norserium** [comment]
@HtmlMak, you are welcome!
