### ISSUE TITLE
Getting errors with new v2.8.7 update

### ISSUE THREAD

**Issue by HassanZahirnia** [advanced-cropper/vue-advanced-cropper#229]
After updating to new `v2.8.7` update I got the following errors:

![image](https://user-images.githubusercontent.com/15275787/212539788-f6a4a7a3-98a3-4af9-b16b-bd92ffc402d7.png)

Not sure why this is happening, don't think it can be my side, since I didn't change my cropper code logic.
Also when installing the package I get the following error, this didn't use to happen:
```
ERR_PNPM_NO_MATCHING_VERSION  No matching version found for vue-advanced-cropper@next
```
Unless I have to specify the version number explicitly. I use `pnpm` btw.

**Comment by Norserium** [comment]
@HassanZahirnia, thank you for your report. The bug is confirmed. I'm looking for the reason.

**Comment by Norserium** [comment]
@HassanZahirnia, try to update to `2.8.8`.

**Comment by HassanZahirnia** [comment]
Hey Norserium! Thanks for the quick update! I updated to `2.8.8` and it works fine! 😊👍

Awesome work as always! 🙌

**Comment by Norserium** [comment]
@HassanZahirnia, thank you for this report!
