### ISSUE TITLE
Can't add vue2 version using yarn

### ISSUE THREAD

**Issue by MoKhawatmi** [advanced-cropper/vue-advanced-cropper#235]
trying to add the v2 version using 'yarn add vue-advanced-cropper@vue-2' results in this error:
Error: vue-advanced-cropper@vue-2 isn't supported by any available resolver.

i can use 'yarn add vue-advanced-cropper' and it will be added fine but it just doesn't work in my vue2 project and has all kinds of errors

**Comment by Norserium** [comment]
Well, it works.
```bash
$ yarn add vue-advanced-cropper@vue-2
```
```bash
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > vue-advanced-cropper@1.11.6" has unmet peer dependency "vue@^2.6.6".
[4/4] Building fresh packages...

success Saved lockfile.
success Saved 4 new dependencies.
info Direct dependencies
└─ vue-advanced-cropper@1.11.6
info All dependencies
├─ classnames@2.3.2
├─ debounce@1.2.1
├─ easy-bem@1.1.1
└─ vue-advanced-cropper@1.11.6
Done in 3.30s.
```

**Comment by MoKhawatmi** [comment]
I don't understand..why am i getting this then? i tried adding from git bash and from windows cmd, same issue..any idea why?
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: vue-advanced-cropper@vue-2 isn't supported by any available resolver
    at zf.getResolverByDescriptor (C:\Users\user\AppData\Local\node\corepack\yarn\3.3.1\yarn.js:391:1647)
    at zf.bindDescriptor (C:\Users\user\AppData\Local\node\corepack\yarn\3.3.1\yarn.js:391:1036)
    at Z (C:\Users\user\AppData\Local\node\corepack\yarn\3.3.1\yarn.js:439:6905)
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 39ms

**Comment by Norserium** [comment]
@MoKhawatmi, what's version of `yarn` do you use? Did you try to use `npm `?

**Comment by MoKhawatmi** [comment]
i tried to use npm and didn't get this error, but i can't just go with it because the project uses yarn install to download packages in the deployment pipeline. as for the version, running yarn --version returns 3.3.1

**Comment by Norserium** [comment]
@MoKhawatmi, how did you install that version? I don't see [here](https://www.npmjs.com/package/yarn?activeTab=versions).

**Comment by Norserium** [comment]
@MoKhawatmi, also you always can try to use:
```
yarn add vue-advanced-cropper@1.11.6
```

**Comment by MoKhawatmi** [comment]
now you mention it, i don't remember installing yarn on my machine at all. i just cloned the project's repo and used yarn install and added new packages too and everything was working. 
trying yarn add vue-advanced-cropper@1.11.6 worked perfectly fine! i added the package and now the cropper code works great! thank you for your help!

**Comment by Norserium** [comment]
@MoKhawatmi, you are welcome. Also you can adjust the version in `package.json` and replace `"1.11.6"` by `"^1.11.6"`.
