### ISSUE TITLE
move-function seems not to work correct

### ISSUE THREAD

**Issue by vollyimnetz** [advanced-cropper/vue-advanced-cropper#238]
I tried to make buttons to move the selection by a certain amount of pixels. I had a look on the [example you provided](https://advanced-cropper.github.io/vue-advanced-cropper/guides/advanced-recipes.html#manipulate-image). But the example seems only to work after the zoom function has been applied. The documentation of the move-function talk about the "visible area" that is moved i guess that is the stencil. But it seems not to work.

So my question is
- is this a bug?
- did the move function move the underlying image or did it move the stencil?
- what is the correct way to move the stencil?

Bonus question 😄: how can i add keypress eventlisteners to move the stencil?

**Comment by Norserium** [comment]
@vollyimnetz, let's go in order.

The answers:
1. It's not a bug.
2. The `move` function moves the image, not the stencil. It will be renamed to `moveImage` in the future.
3. To move the coordinates of the stencil use [`setCoordinates`](https://advanced-cropper.github.io/vue-advanced-cropper/guides/advanced-recipes.html#set-coordinates) method.

The answer on the bonus question depends on the requirements. You can add event listeners to the document and call `setCoordinates` method appropriately.
