### ISSUE TITLE
Cannot destructure property 'height' of 'this.stencilCoordinates' as it is undefined.

### ISSUE THREAD

**Issue by eguvenc** [advanced-cropper/vue-advanced-cropper#239]
I get an height error in vue 3.3.4 version.

![image](https://github.com/advanced-cropper/vue-advanced-cropper/assets/482833/616e8a0b-a2e2-40ce-ab64-d0b8bfde6699)

![image](https://github.com/advanced-cropper/vue-advanced-cropper/assets/482833/a9363513-9fc3-4399-8682-38dceb54bcde)

Here is the codesandbox link.
[https://codesandbox.io/p/github/eguvenc/test/main](https://codesandbox.io/p/github/eguvenc/test/main)

I used this example
[https://advanced-cropper.github.io/vue-advanced-cropper/guides/advanced-stencil.html#result](https://advanced-cropper.github.io/vue-advanced-cropper/guides/advanced-stencil.html#result)

**Comment by Norserium** [comment]
@eguvenc, `stencilCoordinates` is the prop for the stencil component, therefore you should create the component and pass it to `stencil-component`. 

There is [the codesandbox](https://codesandbox.io/s/vue-advanced-cropper-custom-stencil-omseq?file=/src/Stencil.vue).

**Comment by eguvenc** [comment]
It works well :) 🍺 😄 thanks.

**Comment by Norserium** [comment]
@eguvenc, you are welcome!
