### ISSUE TITLE
This package is too perfect, but I do not know why only what a little star

### ISSUE THREAD

**Issue by gspgsp** [advanced-cropper/vue-advanced-cropper#240]
The project is perfect, the documentation is very clear, but in the process of using, I found a small problem, when my picture is relatively high, the Y direction appears scroll bar, when my mouse scrolls, it will trigger the cropper page scrolling, so that the picture is partially larger or smaller, how to set it. This may not be a bug, it may be a js event problem.

**Comment by Norserium** [comment]
@gspgsp, could you record a video?

**Comment by Norserium** [comment]
@gspgsp, any news?

**Comment by Norserium** [comment]
@gspgsp, I close this issue, but feel free to reopen in the future.
