### ISSUE TITLE
Can you zoom out past the base image?

### ISSUE THREAD

**Issue by sebarious** [advanced-cropper/vue-advanced-cropper#243]
This is a brilliant package, so in depth.

One question I do have, I love how you can zoom in to crop an area. But is it possible to zoom out past the base image? As if to make the image smaller within the stencil?

Just thinking where this could be helpful is if you have say pictures of a car or a focal point and you're enforcing an aspect ratio, it'll allow the tool to cover terrible imagery (as if managed by a user).

Is this possible? Am I missing something!

**Comment by Norserium** [comment]
@sebarious, do you mean something like this?

![image](https://github.com/advanced-cropper/vue-advanced-cropper/assets/9862719/32b43574-f354-42a8-a109-d26e01c7b61a)

**Comment by sebarious** [comment]
> @sebarious, do you mean something like this?
> 
> ![image](https://user-images.githubusercontent.com/9862719/253697813-32b43574-f354-42a8-a109-d26e01c7b61a.png)

@Norserium indeed, I found this about 15 minutes after I posted (typical). 

For anyone else thinking the same.. it's [here](https://advanced-cropper.github.io/vue-advanced-cropper/guides/advanced-recipes.html#different-image-restrictions). `imageRestriction` simply needs to be set to `none`. 

Thanks guys this package is awesome!

**Comment by Norserium** [comment]
@sebarious, I'm happy that you like this library. Good luck!
