### ISSUE TITLE
Canvas does not update when image source changes

### ISSUE THREAD

**Issue by Awatatah** [advanced-cropper/vue-advanced-cropper#244]
Hello I am using version `1.11.6` and I came across an issue where if I use the following code:
```typescript
<Cropper
    class="cropper"
    :src="imgSrc"
    :stencil-props="{
      aspectRatio: setAspectRatio(),
    }"
    @change="setNewCoords"
    imageRestriction="fit-area"
/>
```
and once mounted it works great but if the value of `imgSrc` changes, the cropper canvas does not update with the new image.

Is there something I need to do like call a function to reinitialize the Cropper? I'm a little stuck on this.

**Comment by Norserium** [comment]
@Awatatah, could you reproduce your issue in the codesandbox?

**Comment by Awatatah** [comment]
@Norserium I found the issue. I was using the cropper in a modal component that has props (which is how `imgSrc` is set but when the value of the object changed in the parent, the prop did not reflect. I resolved this issue
