### ISSUE TITLE
I am unable to use Cropper in my bootstrap modal.

### ISSUE THREAD

**Issue by ZeeshanAli200** [advanced-cropper/vue-advanced-cropper#249]
the cropper doesnt work on bootstrap modal but as soon as as i implement it on page it works. exception is only for modals and popups
<img width="679" alt="Screenshot 2023-09-20 at 9 46 02 PM" src="https://github.com/advanced-cropper/vue-advanced-cropper/assets/51513202/93b3404d-1cf3-4d3f-aa78-ad0fe5836fce">

**Comment by Norserium** [comment]
@ZeeshanAli200, that's because the cropper shouldn't be rendered inside the component that have `display: none`. It's known issue for modals.

Similar issue #182 with the solution.

**Comment by Norserium** [comment]
@ZeeshanAli200, any news?

**Comment by Norserium** [comment]
@ZeeshanAli200, I close issue, feel free to reopen it.
