### ISSUE TITLE
I want to be able to edit the image preview list by clicking on it.

### ISSUE THREAD

**Issue by jungsikjeong** [advanced-cropper/vue-advanced-cropper#264]
I am doing the following case:

1. Upload multiple images.
![image](https://github.com/advanced-cropper/vue-advanced-cropper/assets/37586626/d5bc647c-9cf3-4cf7-836d-2c65c8aed745)

2. Select the image you want to edit among them.

3. When selected, the following code runs. (Load image with :src)

 ```js
   <Cropper ref="cropper" class="cropper" @change="change" :src="image.src" />
```

But now the problem is
Cropper is not loading through :src.

The code for image is like this.
```js
const image = reactive({
  src: '',
  type: 'image/jpg',
});
```

When you click an image on the screen, the following code runs.
```js
const onImageChange = (e: any) => {
  const allImages = store.getters['imageStore/getImage']; // 변경
  const imageIndex = allImages.findIndex(
    (value: any) => value.toDataURL === e.target.src
  );

  testindex.value = 1;
  if (imageIndex !== -1) {
    image.src = allImages[imageIndex].src;
    isShowFile.value = true;
  }
};
```

As a result of taking console.log, image.src changed well, but
```js
   <Cropper ref="cropper" class="cropper" @change="change" :src="image.src" />
Why is this :src not updated?

```

**Comment by Norserium** [comment]
@jungsikjeong, could you provide more code or reproduce this issue in the codesandbox?

**Comment by Norserium** [comment]
@jungsikjeong, any news?

**Comment by jungsikjeong** [comment]
@Norserium YES. thank you
